services:
  mysql:
    image: mysql:8.4
    container_name: portal-smktelkom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "0899"
      MYSQL_DATABASE: portal_smk_telkom_lampung
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
